---
title: "mapping"
author: "name"
date: "11/3/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
mayorsfoodcourt <- read.csv("Downloads/mayorsfoodcourt.csv")
library(knitr)
library(tidyverse)
library(maps)
library(ggmap)
library(rgdal)
library(devtools)
library(maptools)
library(plyr)
library(raster)
```


```{r}
#cleaning the data
#filter food courts whose licsense status is active and VIOLDTTM in 2018.
boston_food <- mayorsfoodcourt %>% filter(str_detect(VIOLDTTM, "2018")) %>% filter(LICSTATUS=="Active") %>% separate(Location, c("lat","long"),",") %>% filter(!is.na(long) & !is.na(lat))
#covert location into latitude and longtitude. 
boston_food$lat <- as.numeric(gsub("\\(", "", boston_food$lat))
boston_food$long <- as.numeric(gsub(")", "", boston_food$long))
#View(boston_food)

```



```{r}
data(us.cities)
boston <- map.cities(x=boston, country = "MA")
ma<- map_data("county", region = "massachus")
boston_foodmap <- left_join(ma, boston_food)
ggplot() + geom_polygon(data=ma, aes(x=long, y=lat, group=group), color = "cornsilk", fill = "cadetblue") +  
  geom_point(data = boston_food, aes(x = long, y = lat, group=), size = 5) + coord_fixed(1.3)
boston_foodmap <- left_join(ma, boston_food)


```

```{r}
boston_bbox <- make_bbox(lat = lat, lon = long, data = boston_foodmap)
boston_map <- get_map(location = boston_bbox, source = "google", maptype = "hybrid")
ggmap(boston_map) + 
  geom_point(data = boston_food, mapping = aes(x = long, y = lat, color= ViolStatus))


```

```{r}
library(leaflet)
library(sp)
library(magrittr)
library(maps)
library(htmltools)
library(rgdal)
data("quakes")
head(quakes)
m <- leaflet(data = boston_food) %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12) %>% addMarkers(~long, ~lat, popup = ~as.character(businessName), label = ~as.character(businessName))

m %>% addTiles()
m %>% addProviderTiles(providers$Esri.NatGeoWorldMap)



```

